### ISSUE TITLE
Method params doesnt get set for methods with regex in @methodUri

### ISSUE THREAD

**Issue by dotted** [ivolator/restlt#1]
When trying to access a resource using this url: `localhost:3001/api/ranking/heat/1`, I'm using version 2.0.9b

Resource:

```
<?php declare(strict_types=1);
/**
 * @resourceBaseUri /ranking
 */
class Ranking extends Resource {

    /**
     *
     * @method GET
     * @methodUri /heat/([0-9]+)
     */
    public function getRankingsByHeat(string $id) {
        //[...]
    }
}
```

gives me this error:

```
/usr/bin/php7.0 -S localhost:3001 -t /home/dotted/PhpstormProjects/apsisRestServer/public
[Sat Jan 30 22:34:02 2016] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to apsis\resources\Ranking::getRankingsByHeat() must be of the type string, none given in /home/dotted/PhpstormProjects/apsisRestServer/src/resources/Ranking.php:104
Stack trace:
#0 [internal function]: apsis\resources\Ranking->getRankingsByHeat()
#1 /home/dotted/PhpstormProjects/apsisRestServer/vendor/restlt/restlt/lib/restlt/Response.php(237): call_user_func_array(Array, Array)
#2 /home/dotted/PhpstormProjects/apsisRestServer/vendor/restlt/restlt/lib/restlt/Response.php(305): restlt\Response->getRoutedResponse(Object(restlt\routing\RequestRouter))
#3 /home/dotted/PhpstormProjects/apsisRestServer/vendor/restlt/restlt/lib/restlt/Server.php(159): restlt\Response->send()
#4 /home/dotted/PhpstormProjects/apsisRestServer/public/index.php(40): restlt\Server->serve()
#5 {main}
  thrown in /home/dotted/PhpstormProjects/apsisRestServer/src/resources/Ranking.php on line 104
[Sat Jan 30 22:34:02 2016] 127.0.0.1:49634 [500]: /api/ranking/heat/1 - Uncaught TypeError: Argument 1 passed to apsis\resources\Ranking::getRankingsByHeat() must be of the type string, none given in /home/dotted/PhpstormProjects/apsisRestServer/src/resources/Ranking.php:104
Stack trace:
#0 [internal function]: apsis\resources\Ranking->getRankingsByHeat()
#1 /home/dotted/PhpstormProjects/apsisRestServer/vendor/restlt/restlt/lib/restlt/Response.php(237): call_user_func_array(Array, Array)
#2 /home/dotted/PhpstormProjects/apsisRestServer/vendor/restlt/restlt/lib/restlt/Response.php(305): restlt\Response->getRoutedResponse(Object(restlt\routing\RequestRouter))
#3 /home/dotted/PhpstormProjects/apsisRestServer/vendor/restlt/restlt/lib/restlt/Server.php(159): restlt\Response->send()
#4 /home/dotted/PhpstormProjects/apsisRestServer/public/index.php(40): restlt\Server->serve()
#5 {main}
  thrown in /home/dotted/PhpstormProjects/apsisRestServer/src/resources/Ranking.php on line 104
```

According to docs the "/1" in the url should be set in the $id param, but that doesn't appear to be the case.

**Comment by ivolator** [comment]
Hey Sorry for the late response!
I will take a look at that specific case.
Just noticed... Are you using PHP 7?
